### ISSUE TITLE
plugin cmakeed update site has changed

### ISSUE THREAD

**Issue by nwoetzel** [nwoetzel/ansible-role-eclipse#1]
for new versions starting 1.2.0 of cmakeed (1.3.0 and 1.4.0 also), a new update site is available
cmakeed - https://sourceforge.net/projects/cmakeed/files/updates/

**Comment by nwoetzel** [comment]
The feature group is still the same:
- com.cthing.cmakeed.feature.feature.group

**Comment by 15knots** [comment]
Project moved to github.
New update site is https://raw.githubusercontent.com/15knots/cmakeed/master/cmakeed-update/
Lots of windows user with Oracle JDK could not install it from SF (`javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure`) unless they installed the Java Cryptogrphy Extensions installed).

**Comment by nwoetzel** [comment]
Thanks for the info, and sorry for the delay. The update site for cmakeed (in vars/main.yml) is now pointing to the new location.
Thanks for using this channel, to communicate these changes.
I actually also had problems with the JCE (missing in the default jdk download). I have adopted my anisble-role-java-oracle to install the JCE, so that I could install the plugin..
